apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: flux-system
data:
  index.html: |
    <html>
    <head>
      <title>Welcome to My Website</title>
    </head>
    <body>
      <h1>Hello, World!HELLLLLLLL</h1>
    </body>
    </html>
---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: flux-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: test-http
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v1
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        env:
        - name: MSG
          value: This app is version 1
        ports:
        - containerPort: 80

        volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v2
  template:
    metadata:
      labels:
        app: web
        version: v2
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        env:
        - name: MSG
          value: New app is version 2
        ports:
        - containerPort: 80

        volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config